ARG VERSION="8"
FROM node:${VERSION}

WORKDIR /

ENV GHR_VERSION="0.9.0"

RUN apt-get update && \
    apt-get install -y \
    git \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common  \
    libcurl3

# Git Version
RUN wget https://github.com/GitTools/GitVersion/releases/download/5.3.5/gitversion-debian.9-x64-5.3.5.tar.gz
RUN tar -zxvf gitversion-debian.9-x64-5.3.5.tar.gz
RUN mv ./gitversion /bin/gitversion 
RUN chmod +x /bin/gitversion

RUN curl -fSL -o ghr.tar.gz "https://github.com/tcnksm/ghr/releases/download/v${GHR_VERSION}/ghr_v${GHR_VERSION}_linux_amd64.tar.gz"
RUN tar -xvzf ghr.tar.gz
RUN mv ghr_v${GHR_VERSION}_linux_amd64/ghr /usr/local/bin
RUN chown root:root /usr/local/bin/ghr

# Docker
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - 
RUN add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/debian \
    $(lsb_release -cs) \
    stable"
RUN apt-get update && apt-get install -y docker-ce

COPY ./octo /bin/octo
RUN chmod +x /bin/octo

COPY ./withversion /bin/withversion
RUN chmod +x /bin/withversion

RUN rm -r \
    ghr.tar.gz \
    ghr_v0.9.0_linux_amd64