#!/bin/bash

OCTOPUS_FULL_BASE="https://${OCTOPUS_URL}"
OCTOPUS_API_KEY="${OCTOPUS_API_KEY}"

BUILD_NUMBER=${BUILD_NO}
APPLICATION_NAME=${REPO_NAME}
BASE_PATH="./deploy"

PUBLISH=false
CREATE_RELEASE=false
DEPLOY=false

for i in "$@"; do
    case $1 in
        --publish) PUBLISH=true ;;
        --release) CREATE_RELEASE=true ;;
        --deploy) DEPLOY=true ;;
        --buildno) BUILD_NUMBER="$2"; shift ;;
        --appname) APPLICATION_NAME="$2"; shift ;;
        --basepath) BASE_PATH="$2"; shift ;;
        --branch) BRANCH="$2"; shift;; 
        --environment) ENVIRONMENT="$2"; shift;;
    esac
    shift
done

BRANCH="${BRANCH//_/\_}" #Escaping _ because they mean italic in markdown

CREDENTIALS="--server=${OCTOPUS_FULL_BASE} --apiKey=${OCTOPUS_API_KEY}"

# PACKAGE
PACKAGE_COMMAND="--id=${APPLICATION_NAME} --format=zip --version=${BUILD_NUMBER} --overwrite"
PUSH_COMMAND="--package=${APPLICATION_NAME}.${BUILD_NUMBER}.zip --replace-existing ${CREDENTIALS}"
CREATE_RELEASE_COMMAND="--project=${APPLICATION_NAME} --version=${BUILD_NUMBER} --packageversion=${BUILD_NUMBER} --releasenotes=Branch:${BRANCH} ${CREDENTIALS}"
DEPLOY_COMMAND="--project=${APPLICATION_NAME} --version=${BUILD_NUMBER} --deployTo=${ENVIRONMENT} ${CREDENTIALS}"

echo "${PUSH_COMMAND}"

RANDOM_STRING=$(tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 32 | head -n 1)
DATA_CONTAINER_NAME=octopus-data-${RANDOM_STRING}

if $PUBLISH; then
    docker create -v /src --name ${DATA_CONTAINER_NAME} alpine:3.4 /bin/true
    docker cp ${BASE_PATH} ${DATA_CONTAINER_NAME}:/src

    docker run --rm --volumes-from ${DATA_CONTAINER_NAME} octopusdeploy/octo pack ${PACKAGE_COMMAND}
    docker run --rm --volumes-from ${DATA_CONTAINER_NAME} octopusdeploy/octo push ${PUSH_COMMAND}

    docker rm ${DATA_CONTAINER_NAME} --force
fi

if $CREATE_RELEASE; then
    docker run --rm octopusdeploy/octo create-release ${CREATE_RELEASE_COMMAND}
fi

if $DEPLOY; then
    docker run --rm octopusdeploy/octo deploy-release ${DEPLOY_COMMAND}
fi