build_container: &build_container
  docker:
    - image: circleci/node:latest
  working_directory: ~/urban_build
  steps:
    - checkout: { path: ~/urban_build }
    - setup_remote_docker
    - run:
        name: Docker Login
        command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
    - run:
        name: Build And Push
        command: |
          #!/bin/bash
          IFS=’,’ read -ra arr <<< "$VERSIONS"
          for i in "${arr[@]}"; do
              docker build --build-arg VERSION=${i} -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:${CODE_TYPE}${i}-latest ./${CODE_TYPE}/.
              docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:${CODE_TYPE}${i}-latest
          done
version: 2
jobs:
  build_node_images:
    <<: *build_container
    environment:
      VERSIONS: "12,13"
      CODE_TYPE: node

  build_dotnet_images:
    <<: *build_container
    environment:
      VERSIONS: "3.1.100-bionic"
      CODE_TYPE: dotnet

workflows:
  version: 2
  build:
    jobs:
      - build_node_images
      - build_dotnet_images