build_container: &build_container
  docker:
      - image: 'docker:17.05.0-ce-git'
  working_directory: ~/thenerdybrewingco
  steps:
    - checkout: { path: ~/thenerdybrewingco }
    - setup_remote_docker
    - run:
        name: Docker Login
        command: docker login --username $DOCKER_USER --password $DOCKER_PASS 
    - run:
        name: Build And Push
        command: |
          docker build --build-arg VERSION=${VERSION} -t thenerdybrewingco/$CIRCLE_PROJECT_REPONAME:${CODE_TYPE}${i}-latest ./${CODE_TYPE}/.
          docker push thenerdybrewingco/$CIRCLE_PROJECT_REPONAME:${CODE_TYPE}${i}-latest

version: 2
jobs:
  build_node_12_images:
    <<: *build_container
    environment:
      VERSIONS: "12"
      CODE_TYPE: node
  
  build_node_13_images:
    <<: *build_container
    environment:
      VERSIONS: "13"
      CODE_TYPE: node

  build_dotnet_images:
    <<: *build_container
    environment:
      VERSIONS: "3.1.100-bionic"
      CODE_TYPE: dotnet

workflows:
  version: 2
  build:
    jobs:
      - build_node_12_images:
          context: THENERDYBREWINGCO
      - build_node_13_images:
          context: THENERDYBREWINGCO
      - build_dotnet_images:
          context: THENERDYBREWINGCO