name: Build And Release

on: [ push ]

jobs:
  node-job:
    runs-on: ubuntu-latest
    container: docker
    
    strategy:
      matrix: 
        node-version: [ 16 ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: overtheairbrew/build:node-${{ matrix.node-version }}
          file: Dockerfile.node
          build-args: |
            VERSION=${{ matrix.node-version }}