name: Build And Release

on: [ push ]

jobs:
  node-job:
    runs-on: ubuntu-latest
    container: docker
    
    strategy:
      matrix: 
        node-version: [ 12, 14, 16 ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          docker buildx build --tag overtheairbrew/build:node-${{ matrix.node-version }} -f Dockerfile.node --build-arg VERSION=${{ matrix.node-version }} --platform=linux/amd64,linux/arm64,linux/arm/v7 --push .