name: Build And Release

on: [ push ]

jobs:
  node-job:
    runs-on: ubuntu-latest
    container: docker
    
    strategy:
      matrix: 
        node-version: [ 12, 14 ]

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build
        run: |
          docker build --build-arg VERSION=${{ matrix.node-version }} -t overtheairbrew/build:node-${{ matrix.node-version }} .
          docker push overtheairbrew/build:node-${{ matrix.node-version }}